In [1]:
import numpy as np

### NUMPY

### Exercise 1

In [2]:
a = np.array([
    [1, 6], 
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

In [3]:
mean_a = np.array([0., 0.])

In [4]:
np.mean(a, axis=0, out=mean_a)

array([2. , 8.4])

In [5]:
mean_a

array([2. , 8.4])

### Exercise 2

In [6]:
a_centered = a - mean_a

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Exercise 3

In [8]:
a_centered_trans = a_centered.transpose()

In [13]:
a_centered_sp = a_centered_trans[0]@a_centered_trans[1]
a_centered_sp

8.0

In [15]:
a_centered_sp / (len(a_centered)-1)

2.0

### Exercise 4

In [16]:
a_trans = a.transpose()

In [17]:
np.cov(a_trans)

array([[1. , 2. ],
       [2. , 4.3]])

### PANDAS

In [1]:
import pandas as pd

### Exercise 1

In [17]:
col_a = ['author_id', 'author_name']
data_a = [[1, 'Тургенев'],[2, 'Чехов'],[3, 'Островский']]
df_a = pd.DataFrame(data = data_a, columns = col_a)

In [18]:
df_a

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [20]:
col_b = ['author_id', 'book_title', 'price']
data_b = [
    [1, 'Отцы и дети', 450], 
    [1, 'Рудин', 300], 
    [1, 'Дворянское гнездо', 350], 
    [2, 'Толстый и тонкий', 500], 
    [2, 'Дама с собачкой', 450], 
    [3, 'Гроза', 370], 
    [3, 'Таланты и поклонники', 290]
]
df_b = pd.DataFrame(data = data_b, columns = col_b)

In [21]:
df_b

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Exercise 2

In [22]:
authors_price = pd.merge(left = df_a, right = df_b, left_on = 'author_id', right_on = 'author_id')

In [23]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Exercise 3

In [28]:
top5 = authors_price.sort_values(by=['price'], ascending = False).head(5)

In [29]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Exercise 4

In [121]:
result = authors_price.groupby('author_name').price.agg(
minPrice = 'min',
maxPrice = 'max',
meanPrice = 'mean'
)
result

minPrice  maxPrice   meanPrice
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

### Ecercise 5

In [129]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [133]:
book_info = authors_price.pivot_table(
    values = 'price', 
    index = 'author_name', 
    columns = 'cover', 
    aggfunc = 'sum', 
    fill_value= 0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950